WeatherApiCall/Controllers/WeatherDataController.cs
using Newtonsoft.Json.Linq;
using NLog;

using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using WeatherApiCall.Models;

namespace WeatherApiCall.Controllers
{
    public class WeatherDataController : Controller
    {
        Logger Logger = LogManager.GetCurrentClassLogger();

        // GET: WeatherData
        public ActionResult Get_User_Input()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Show_Weather_Data(string location)
        {

            List<WeatherDataModel> modellist = new List<WeatherDataModel>();

            using (var client = new HttpClient())
            {
                try { 
               
               // X - RapidAPI - Key
                client.DefaultRequestHeaders.Add("X-RapidAPI-Host", "community-open-weather-map.p.rapidapi.com");
                client.DefaultRequestHeaders.Add("X-RapidAPI-Key", "ENTER YOUR FREE KEY FROM RAPID API");    
                client.BaseAddress = new Uri("https://community-open-weather-map.p.rapidapi.com/");
               // client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                var responseTask = client.GetAsync("weather?&q=" + location);
                // var responseTask = client.GetAsync("weather?q="+location);
                responseTask.Wait();
                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    //try
                    //{

                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();
                        var weatherdata = readTask.Result.ToString();
                        // var lt = JsonConvert.DeserializeObject<WeatherDataModel>(listDestinations);


                        var datakeyvalue = JObject.Parse(weatherdata);

                        WeatherDataModel objweatherdata = new WeatherDataModel();

                        string timez;
                        double timezone = ((Convert.ToDouble(datakeyvalue["timezone"])) / 60) / 60;
                        objweatherdata.Timezone = timezone.ToString().First() != '-' ? (timez = "GMT" + "+" + timezone) : (timez = "GMT" + " " + timezone);

                        // epoch to date and time

                        double SunriseEpoch = Convert.ToDouble(datakeyvalue["sys"]["sunrise"]);
                        objweatherdata.Sunrise = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(SunriseEpoch).AddHours(timezone);
                        // string SunriseDate = dateTime.ToShortDateString() + " " + dateTime.ToShortTimeString();

                        double SunsetEpoch = Convert.ToDouble(datakeyvalue["sys"]["sunset"]);
                        objweatherdata.Sunset = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(SunsetEpoch).AddHours(timezone);
                        // string SunsetDate = dateTime.ToShortDateString() + " " + dateTime.ToShortTimeString();




                        objweatherdata.Longitude = Convert.ToDouble(datakeyvalue["coord"]["lon"]);
                        objweatherdata.Latitude = Convert.ToDouble(datakeyvalue["coord"]["lat"]);
                        objweatherdata.Temp = (Convert.ToDouble(datakeyvalue["main"]["temp"]) - 273.15);
                        objweatherdata.weathertype = Convert.ToString(datakeyvalue["weather"][0]["main"]);
                        objweatherdata.weatherdescription = Convert.ToString(datakeyvalue["weather"][0]["description"]);
                        objweatherdata.Pressure = Convert.ToDouble(datakeyvalue["main"]["pressure"]);
                        objweatherdata.Humidity = Convert.ToDouble(datakeyvalue["main"]["humidity"]);
                        objweatherdata.Temp_Min = ((Convert.ToDouble(datakeyvalue["main"]["temp_min"])) - 273.15);
                        objweatherdata.Temp_Max = (Convert.ToDouble(datakeyvalue["main"]["temp_max"])) - 273.15;
                        objweatherdata.Windspeed = Convert.ToDouble(datakeyvalue["wind"]["speed"]);
                        objweatherdata.visibility = Convert.ToInt32(datakeyvalue["visibility"])/1000;
                       



                        objweatherdata.CountryName = Convert.ToString(datakeyvalue["name"]);

                        // epoch timezone to normal timezone





                        ViewBag.Location = Convert.ToString(datakeyvalue["name"]);

                        modellist.Add(objweatherdata);


                        return Json(modellist, JsonRequestBehavior.AllowGet);

                      //  return View(modellist);
                   
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Server error try after some time.");
                }
                }
                catch (Exception ex)
                {
                    Logger.Error(ex, "Error Occured in Show_Weather_Data" + DateTime.Now.ToShortTimeString());
                    List<string> Errorlist = new List<string>();
                    //  Errorlist.Add("Some Error Occured. Please Try Again");
                    Errorlist.Add(Convert.ToString(ex));
                    //return Json(null, JsonRequestBehavior.AllowGet);
                    return Json(Errorlist, JsonRequestBehavior.AllowGet);

                }
            }
            return View(modellist);


        }

     
        public JsonResult Ajax_Show_Weather_Data(string location)
        {
            
            //List<WeatherDataModel> modellist = new List<WeatherDataModel>();

            using (var client = new HttpClient())
            {
                try
                {
                    //X - RapidAPI - Key
                    client.DefaultRequestHeaders.Add("X-RapidAPI-Host", "community-open-weather-map.p.rapidapi.com");
                    client.DefaultRequestHeaders.Add("X-RapidAPI-Key", "ENTER YOUR FREE KEY FROM RAPID API");
                    client.BaseAddress = new Uri("https://community-open-weather-map.p.rapidapi.com/");
                    client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                    var responseTask = client.GetAsync("weather?units=%22metric%22+or+%22imperial%22&mode=xml%2C+html&q=" + location);
                    // var responseTask = client.GetAsync("weather?units="+unit +"&mode=xml%2C+html&q=" + location);
                    // var responseTask = client.GetAsync("q="+location);

                    responseTask.Wait();
                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {

                        var readTask = result.Content.ReadAsStringAsync();
                        readTask.Wait();
                        var weatherdata = readTask.Result.ToString();
                        var datakeyvalue = JObject.Parse(weatherdata);


                        WeatherDataModel objweatherdata = new WeatherDataModel();

                        string timez;
                        double timezone = ((Convert.ToDouble(datakeyvalue["timezone"])) / 60) / 60;
                        objweatherdata.Timezone = timezone.ToString().First() != '-' ? (timez = "GMT" + "+" + timezone) : (timez = "GMT" + " " + timezone);

                        double SunriseEpoch = Convert.ToDouble(datakeyvalue["sys"]["sunrise"]);
                        objweatherdata.Sunrise = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(SunriseEpoch).AddHours(timezone);
                        objweatherdata.stringSunrise = objweatherdata.Sunrise.ToString();
                        double SunsetEpoch = Convert.ToDouble(datakeyvalue["sys"]["sunset"]);
                        objweatherdata.Sunset = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(SunsetEpoch).AddHours(timezone);
                        objweatherdata.stringSunset = objweatherdata.Sunset.ToString();
                        objweatherdata.Longitude = Convert.ToDouble(datakeyvalue["coord"]["lon"]);
                        objweatherdata.Latitude = Convert.ToDouble(datakeyvalue["coord"]["lat"]);
                        objweatherdata.Temp = (Convert.ToDouble(datakeyvalue["main"]["temp"]) - 273.15);
                        objweatherdata.Temp = (int)objweatherdata.Temp;
                        objweatherdata.weathertype = Convert.ToString(datakeyvalue["weather"][0]["main"]);
                        objweatherdata.weatherdescription = Convert.ToString(datakeyvalue["weather"][0]["description"]);
                        objweatherdata.Pressure = Convert.ToDouble(datakeyvalue["main"]["pressure"]);
                        objweatherdata.Humidity = Convert.ToDouble(datakeyvalue["main"]["humidity"]);
                        objweatherdata.Temp_Min = ((Convert.ToDouble(datakeyvalue["main"]["temp_min"])) - 273.15);
                        objweatherdata.Temp_Min = (int)objweatherdata.Temp_Min;
                        objweatherdata.Temp_Max = (Convert.ToDouble(datakeyvalue["main"]["temp_max"])) - 273.15;
                        objweatherdata.Temp_Max = (int)objweatherdata.Temp_Max;
                        objweatherdata.Windspeed = Convert.ToDouble(datakeyvalue["wind"]["speed"]);
                        objweatherdata.visibility = Convert.ToInt32(datakeyvalue["visibility"]) / 1000;
                        objweatherdata.CountryName = Convert.ToString(datakeyvalue["name"]);
                        objweatherdata.icon = Convert.ToString(datakeyvalue["weather"][0]["icon"]);

                        ViewBag.Location = Convert.ToString(datakeyvalue["name"]);

                        // modellist.Add(objweatherdata);

                        return Json(objweatherdata, JsonRequestBehavior.AllowGet);

                    }
                    else
                    {

WeatherApiCall/Views/WeatherData/Get_User_Input.cshtml
@using WeatherApiCall.Models;
@model WeatherDataModel

@{
    Layout = null;
    var imgSrc = "";

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Get_User_Input</title>
</head>
<body>
    <div>
        <center>
            <h1>Weather Api </h1>
        </center>
        <fieldset>
            <legend>Weather Search</legend>
            <br />
            <br />
            @using (Html.BeginForm("Show_Weather_Data", "WeatherData", FormMethod.Post))
            { }
            @*@Html.Label("Select Mode")

            @Html.DropDownListFor(x => x.Mode, new List<SelectListItem>
            { new SelectListItem {Text="Xml",Value="Xml" }
            , new SelectListItem{Text="Json", Value="Json"} }
            , "--Select Type--")*@


            @Html.Label("Select Country")

            @Html.DropDownListFor(x => x.Location, new List<SelectListItem>
{ new SelectListItem {Text=" Delhi India",Value="delhi,in" }
,new SelectListItem {Text=" Mumbai India",Value="mumbai,in" }
,new SelectListItem {Text=" lahore Pakistan",Value="lahore,pk" }
,new SelectListItem {Text=" Newyork Usa",Value="new york,us" }
,new SelectListItem {Text=" Sydney Australia",Value="sydney,aus" }
, new SelectListItem{Text="London", Value="london,uk"}
, new SelectListItem{Text="Amazonas", Value="Amazonas,bra"}
}
, "--Select Country--", new {  @class ="locationdropdown"})

            @*@Html.Label("Select Unit")

            @Html.DropDownListFor(x => x.Unit, new List<SelectListItem>
            { new SelectListItem {Text="metric",Value="metric" }
            , new SelectListItem{Text="imperial", Value="imperial"} }
            , "--Select Unit--" ,new { @class = "unitdropdown" })*@

            <input type="submit" value="Get Weather" name="GetWeather" id="GetWeather" />


            <div id="TypeError" style="color:red; display:none">Error</div>
            @*<div id="WeatherData" style="color:red; display:none"></div>*@
            <br />

        </fieldset>


    </div>
    <br />
    <br />
    <div id="WeatherData" style="display:none">
        <center>
            <h1>
                <div id="Cityname"></div>
            </h1>
        </center>
        <img id="user_img"
             src="@imgSrc"
             alt=""
             height="100"
             width="120"
             style="border:hidden; align-content:stretch" />
        
        <table id="weathertable" style="display:none">

            <tr>
                <td> @Html.Label("Latitude") : </td>
                <td><div id="Latitude"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Longitude") : </td>
                <td><div id="Longitude"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Weather Type") : </td>

                <td><div id="WeatherType"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Weather Description") : </td>
                <td><div id="WeatherDescription"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Temperature") : </td>
                <td><div id="Temperature"></div> </td>
            </tr>
            <tr>
                <td> @Html.Label("Min Temp") : </td>
                <td><div id="MinTemp"></div></td>

                <td>@Html.Label("Max Temp") : </td>
                <td><div id="MaxTemp"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Pressure") : </td>
                <td><div id="Pressure"></div> </td>
            </tr>
            <tr>
                <td>@Html.Label("Visibility") : </td>
                <td><div id="Visibility"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("WindSpeed") : </td>
                <td><div id="WindSpeed"></div> </td>
            </tr>
            <tr>
                <td>@Html.Label("Sunrise") : </td>
                <td><div id="Sunrise"></div> </td>

                <td>@Html.Label("Sunset") : </td>
                <td><div id="Sunset"></div></td>
            </tr>
            <tr>
                <td>@Html.Label("Timezone") : </td>
                <td><div id="Timezone"></div></td>
            </tr>
        </table>
        <br />
        <br />
        <center>
            <h2> @Html.ActionLink("Clear Search", "Get_User_Input")</h2>
        </center>
    </div>
</body>
</html>
<script src="~/Script/jquery-3.4.1.min.js"></script>
<link href="~/Script/Color.css" rel="stylesheet" />

<script type="text/javascript">
    //$(".locationdropdown").change(
    $("#GetWeather").click(
        function () {
            // $("#WeatherData").empty();
            $("#WeatherData").removeAttr("background-image");
            $("#WeatherData").hide();
            var location = $(".locationdropdown").val();
            
            
            $.ajax({
                type: "GET",
                url: "/WeatherData/Ajax_Show_Weather_Data?location=" + location,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    
                    if (response == null) {
                        alert("Failed To Get Response Due To Incorrect Input");
                    }
                  


                    $('#user_img').attr('src', "http://openweathermap.org/img/w/" + response.icon + ".png");
                    $("#WeatherData").removeAttr("background-image");
                    $("#WeatherData").css("background-color", "null");
                    $("#Latitude").text(response.Longitude);
                    $("#Longitude").text(response.Latitude);
                    $("#WeatherType").text(response.weathertype);
                    $("#WeatherDescription").text(response.weatherdescription);
                    $("#Temperature").text(response.Temp + " " + "°C");
                    $("#MinTemp").text(response.Temp_Max + " " + "°C");
                    $("#MaxTemp").text(response.Temp_Min + " " + "°C");
                    $("#Pressure").text(response.Pressure + " " + "hpa");
                    $("#Visibility").text(response.visibility + " " + "Km");
                    $("#WindSpeed").text(response.Windspeed + " " + "mph");
                    $("#Sunrise").text("☼" + " " + response.stringSunrise);
                    $("#Sunset").text("☼" + " " + response.stringSunset);
                    $("#Timezone").text(response.Timezone);
                    $("#Cityname").text("Weather Of " + response.CountryName);
                    //$("#Latitude").text(response.visibility);


                    var res = response.weathertype;

                    //if(res.toLowerCase() == "rain") {
                    //    var Rain = "/Script/RainImage.jpg";
                    //    $("#WeatherData").css("background-image", "url(" + Rain + ")");
                    //    $("#WeatherData").css("color", "yellow");
                    //}

                    //else if (res.toLowerCase() == "haze") {
                    //    var Haze = "/Script/HazeWeather.jpg";
                    //    $("#WeatherData").css("background-image", "url(" + Haze + ")");
                    //}

                    //else if (res.toLowerCase() == "sunny") {
                    //    var Sunny = "/Script/SunnyDay.jpg";
                    //    $("#WeatherData").css("background-image", "url(" + Sunny + ")");
                    //    $("#WeatherData").attr("background-size", "cover");

                    //}
                    //else {
                    //    var defaultimg = "/Script/file-20180320-31608-mzi52w.jpg";
                    //    $("#WeatherData").css("background-image", "url(" + defaultimg + ")");
                    //}

                    $("#weathertable").show();
                    $("#WeatherData").show();



                },
                failure: function (response) {
                    alert(response);
                }
            });



        });




</script>

<link href="~/Script/weatherdatabg.css" rel="stylesheet" />

WeatherApiCall/Views/WeatherData/Show_Weather_Data.cshtml
@using WeatherApiCall.Models;
@model List<WeatherDataModel>

@{
    /**/

    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Show_Weather_Data</title>
</head>
<body style="color:black">
    <div>
        <center>
            <h1>Weather Details </h1>
        </center>
        <fieldset>
            <legend><b>Weather Of @ViewBag.location </b></legend>
            <br />
            <br />
            @foreach (var item in Model)
            {
            <table>
                <tr>
                    <td> @Html.Label("Latitude") : </td>
                    <td>@item.Latitude</td>
                </tr>
                <tr>
                    <td>@Html.Label("Longitude") : </td>
                    <td>@item.Longitude</td>
                </tr>
                <tr>
                    <td>@Html.Label("Weather Type") : </td>
                    <td>@item.weathertype</td>
                </tr>
                <tr>
                    <td>@Html.Label("Weather Description") : </td>
                    <td>@item.weatherdescription</td>
                </tr>
                <tr>
                    <td>@Html.Label("Temperature") : </td>
                    <td>@item.Temp °C</td>
                </tr>
                <tr>
                    <td> @Html.Label("Min Temp") : </td>
                    <td>@item.Temp_Min °C</td>

                    <td>@Html.Label("Max Temp") : </td>
                    <td>@item.Temp_Max °C</td>
                </tr>
                <tr>
                    <td>@Html.Label("Pressure") : </td>
                    <td>@item.Pressure pascal</td>
                </tr>
                <tr>
                    <td>@Html.Label("Visibility") : </td>
                    <td>@item.visibility</td>
                </tr>
                <tr>
                    <td>@Html.Label("WindSpeed") : </td>
                    <td>@item.Windspeed mph</td>
                </tr>
                <tr>
                    <td>@Html.Label("Sunrise") : </td>
                    <td>☼ @item.Sunrise </td>

                    <td>@Html.Label("Sunset") : </td>
                    <td>☼ @item.Sunset</td>
                </tr>
                <tr>
                    <td>@Html.Label("Timezone") : </td>
                    <td>@item.Timezone</td>
                </tr>
            </table>
            }
            <br />
            <br />
            @Html.ActionLink("Back To Search", "Get_User_Input")


        </fieldset>
    </div>
</body>
</html>

<script src="~/Script/jquery-3.4.1.min.js"></script>
<link href="~/Script/Color 1.css" rel="stylesheet" />